export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const LOCAL_TO_REDUX = 'LOCAL_TO_REDUX';

export const ADD_COMMENT = 'ADD_COMMENT';
export const CHANGE_ORDER_OF_REDUX_ITEMS = 'CHANGE_ORDER_OF_REDUX_ITEMS';
export const CHANGE_CB_STATUS = 'CHANGE_CB_STATUS';


